/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bunnyblue_droidncm_dump_NcmDumper */

#ifndef _Included_io_bunnyblue_droidncm_dump_NcmDumper
#define _Included_io_bunnyblue_droidncm_dump_NcmDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bunnyblue_droidncm_dump_NcmDumper
 * Method:    ncpDump
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bunnyblue_droidncm_dump_NcmDumper_ncpDump
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
